DROP TABLE IF EXISTS template;
CREATE TABLE template (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE,
	data JSON NOT NULL
);

DROP TABLE IF EXISTS session;
CREATE TABLE session (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	patient_number TEXT NOT NULL,
	date_time TEXT NOT NULL DEFAULT (datetime('now')),
	data JSON NOT NULL
);